#!/bin/bash

set -e
set -o xtrace

apt-get install -y procps

SCRIPTDIR=$(dirname $0)

install -c -g root -o root -m 0644 ${SCRIPTDIR}/99-kubernetes-cri.conf  /etc/sysctl.d/99-kubernetes-cri.conf

install -d -g root -o root -m 0755 /etc/modules-load.d/

install -c -g root -o root -m 0644 ${SCRIPTDIR}/kubernetes.conf /etc/modules-load.d/kubernetes.conf
