#!/bin/bash

set -e
set -o xtrace

regexp="^v([0-9]+\.){2}[0-9]$"
if [[ -z ${KUBERNETES_VERSION+x} ]]; then
    export KUBERNETES_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
elif ! [[ $KUBERNETES_VERSION =~ $regexp ]]; then
    echo "Kubernetes version : $KUBERNETES_VERSION is not a valid version like v1.20.1" 1&>2
    exit 1
fi

if ! [[  $ARCH =~ ^(arm64|amd64)$ ]]; then
    echo "Arch must be 'amd64' or 'arm64'" 1&>2
    exit 1
fi
